"use client";
// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { I18nextProvider } from "react-i18next";
import { i18n } from "@/shared/utils/i18next";
import { AppThemeProvider } from "@/shared/customization/AppThemeProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Smart Store",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <I18nextProvider i18n={i18n}>
          <AppThemeProvider>{children}</AppThemeProvider>
        </I18nextProvider>
      </body>
    </html>
  );
}
