export { AccountSettings as AccountSettingsIcon } from "./AccountSettings";
export { AddIcon } from "./Add";
export { AddImageIcon } from "./AddImageIcon";
export { AddNewIcon } from "./AddNew";
export { AddNewCard as AddNewCardIcon } from "./AddNewCard";
export { Address as AddressIcon } from "./Address";
export { Apple as AppleIcon } from "./Apple";
export { Approve as ApproveIcon } from "./Approve";
export { Arrow as ArrowIcon } from "./Arrow";
export { ArrowButton } from "./ArrowButton";
export { ArrowCollapseIcon } from "./ArrowCollapseIcon";
export { ArrowDown } from "./ArrowDown";
export { ArrowUp } from "./ArrowUp";
export { BarChart as BarChartIcon } from "./BarChart";
export { BlankOrderIcon } from "./BlankOrder";
export { BusinessRules as BusinessRulesIcon } from "./BusinessRules";
export { CallIcon } from "./Call";
export { CameraIcon } from "./Camera";
export { Cards as CardsIcon } from "./Cards";
export { CareCenters as CareCentersIcon } from "./CareCenters";
export { ChatMessageIcon } from "./ChatMessage";
export { CheckmarkIcon } from "./Checkmark";
export { CirclePlus as CirclePlusIcon } from "./CirclePlus";
export { Cities as CitiesIcon } from "./Cities";
export { ClockIcon } from "./Clock";
export { Close as CloseIcon } from "./Close";
export { CloudErrorIcon } from "./CloudError";
export { CollapseIcon } from "./CollapseIcon";
export { Customer, Customer as CustomerIcon } from "./Customer";
export { DecrementIcon } from "./Decrement";
export { DeliveringIcon } from "./DeliveringIcon";
export { DeliveryIcon } from "./DeliveryIcon";
export { DoctorIcon } from "./Doctor";
export { DoneIcon } from "./Done";
export { DragAndDropImageIcon } from "./DragAndDropImageIcon";
export { EditIcon } from "./Edit";
export { EmptyBoxIcon } from "./EmptyBox";
export { EmptyNotificationIcon } from "./EmptyNotificationIcon";
export { ErrorIcon } from "./Error";
export { Excel as ExcelIcon } from "./Excel";
export { ExpandIcon } from "./ExpandIcon";
export { EyeIcon } from "./Eye";
export { EyeOffIcon } from "./EyeOffIcon";
export { Facebook } from "./Facebook";
export { Filter as FilterIcon } from "./Filter";
export { FlowerIcon } from "./Flower";
export { Globe as GlobeIcon } from "./Globe";
export { LanguageGlobeIcon } from "./GlobeIcon";
export { Gmail } from "./Gmail";
export { GooglePlay } from "./GooglePlay";
export { HeaderCustomerIcon } from "./HeaderCustomer";
export { HeaderHeartIcon } from "./HeaderHeart";
export { HeaderShoppingIcon } from "./HeaderShopping";
export { Heart as HeartIcon } from "./Heart";
export { HomeAddressIcon } from "./HomeAddress";
export { Hospitals as HospitalsIcon } from "./Hospitals";
export { ImageIcon } from "./Image";
export { Important as ImportantIcon } from "./Important";
export { IncrementIcon } from "./Increment";
export { Line } from "./Line";
export { Location as LocationIcon } from "./Location";
export { LocationSmallIcon } from "./LocationSmall";
export { Logout as LogoutIcon } from "./Logout";
export { MadaIcon } from "./MadaIcon";
export { MapMarkerIcon } from "./MapMarker";
export { MarkerIcon } from "./Marker";
export { MasterCardIcon } from "./MasterCardIcon";
export { Medication as MedicationIcon } from "./Medication";
export { MenuIcon } from "./Menu";
export { MicrophoneIcon } from "./Microphone";
export { ModalClose as ModalCloseIcon } from "./ModalClose";
export { MoneyIcon } from "./Money";
export { MotorcycleIcon } from "./Motorcycle";
export { MyCards as MyCardsIcon } from "./MyCards";
export { MyCart as MyCartIcon } from "./MyCart";
export { MyLocationIcon } from "./MyLocation";
export { MyPrescription as MyPrescriptionIcon } from "./MyPrescription";
export { NextIcon } from "./Next";
export { NothingFoundIcon } from "./NothingFound";
export { Notification as NotificationIcon } from "./Notification";
export { OkayIcon } from "./Okay";
export { OrderBox as OrderBoxIcon } from "./OrderBox";
export { OrderDetailsIcon } from "./OrderDetails";
export { OrderPharmacyIcon } from "./OrderPharmacy";
export { OrdersIcon } from "./OrdersIcon";
export { PasswordIcon } from "./PasswordIcon";
export { PencilIcon } from "./Pencil";
export { Pharmacies as PharmaciesIcon } from "./Pharmacies";
export { PharmacyIcon } from "./Pharmacy";
export { PickupIcon } from "./Pickup";
export { PillSmallIcon } from "./PillSmall";
export { PlaceMarkerIcon } from "./PlaceMarker";
export { Plus as PlusIcon } from "./Plus";
export { Prescription as PrescriptionIcon } from "./Prescription";
export { Prescription2 as PrescriptionIcon2 } from "./Prescription2";
export { PrevButton } from "./PrevButton";
export { PreviousIcon } from "./Previous";
export { Product as ProductIcon } from "./Product";
export { Provider as ProviderIcon } from "./Provider";
export { RatingIcon } from "./RatingIcon";
export { Reboot as RebootIcon } from "./Rebot";
export { Receipt as ReceiptIcon } from "./Receipt";
export { ErX as ErXIcon } from "./RX";
export { SearchIcon } from "./Search";
export { SendIcon } from "./Send";
export { Settings as SettingsIcon } from "./Settings";
export { ShopIcon } from "./Shop";
export { Shopping as ShoppingIcon } from "./Shopping";
export { Show } from "./Show";
export { SignoutIcon } from "./SignoutIcon";
export { SpeechIcon } from "./Speech";
export { SpeechBubbleIcon } from "./SpeechBubble";
export { SquareIcon } from "./Square";
export { StarIcon } from "./Star";
export { SuccessIcon } from "./SuccessIcon";
export { TrackingIcon } from "./Tracking";
export { TrashIcon } from "./Trash";
export { Upload as UploadIcon } from "./Upload";
export { UserIcon } from "./UserIcon";
export { UsersGroup as UsersGroupIcon } from "./UsersGroup";
export { Versions as VersionsIcon } from "./Versions";
export { VisaCardIcon } from "./VisaCardIcon";
export { Vision as VisionIcon } from "./Vision";
export { WhatsappIcon } from "./Whatsapp";
